name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet publish -c Release -r win-x64 --self-contained

    - name: Zip build
      run: |
        cd ./BackroomsProject/bin/Release/net6.0/win-x64/publish/
        powershell Compress-Archive -Path * -DestinationPath ./build.zip

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: ./BackroomsProject/bin/Release/net6.0/win-x64/publish/build.zip
